name: deploy

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set docker tag
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          GIT_BRANCH=${GIT_BRANCH//\//_} # Replace / with _
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, cache and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/emperdeon/${{ github.event.repository.name }}:${{ env.GIT_BRANCH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GITHUB_REF=${{ env.GITHUB_REF }}
